# Name Service
spring:
  application:
    name: discover-service

# Port Service
server:
  port: 8007

# API URL
resource:
  api:
    url: 
      base: https://api.themoviedb.org/3/discover/movie
      image: https://image.tmdb.org/t/p/w342
    key: "?api_key=0a2eea61408ba5facdd057f7d11d2f58"
    language: "&language=fr-FR"

# DEBUG    
debug: true

# LOG
#logging:
#  path: /var/log/discover-service/
#  file: /var/log/discover-service/discover-service.log

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/